### ISSUE TITLE
Jakarta EE 10 schemas

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-schemas#13]
What is the plan for Jakarta EE 10.

I know schema updates will be required for Servlet 6.0 and JSP 3.1. I'm happy to provide a PR for that but I need some direction in terms of what is required.

**Comment by ivargrimstad** [comment]
Thanks for bringing it up @markt-asf!
The schemas shall be published the same way as we did for Jakarta EE 9. I'll set up the structure for Jakarta EE 10 and provide instructions for how to add the schemas for the individual specs.

**Comment by markt-asf** [comment]
Thanks. If you ping this issue when things are ready I can do the Servlet and JSP updates.

**Comment by ivargrimstad** [comment]
The README file now has some instructions for how to do it.
It boils down to:
1. Update the schema definition source file (`.xsds` in the `src` folder) with the new version  (both file name and content)
2. Build (ant)
3. Fix the tests if failing
4. Grab the generated scheme definition (`.xsd`) from the build folder and publish following this [guide](https://eclipse-ee4j.github.io/jakartaee-platform/publish-xml-schemas).

I published the jakartaee_10.xsd [here]((https://jakarta.ee/xml/ns/jakartaee/#10) as an example with https://github.com/jakartaee/jakarta.ee/pull/1265.

Let me know if you need anything else!

**Comment by markt-asf** [comment]
Thanks. That is everything I needed. PR on the way for the JSP and Servlet version updates. Additional updates may follow depending on discussions in the spec projects about new features.
