### ISSUE TITLE
Remove updates to ejb-jar_4_0.xsd for Jakarta EE 10

### ISSUE THREAD

**Issue by tkburroughs** [eclipse-ee4j/jakartaee-schemas#34]
The Jakarta Enterprise Beans specification will NOT be updated for Jakarta EE 10, but will remain at spec level 4.0.

The ejb-jar_4_0.xsd must remain compatible with Jakarta EE 9.

It appears the following was changed in the 4.0 XSD, which would cause it to no longer work for a Jakarata EE 9 implementation:

  <xsd:include schemaLocation="jakartaee_10.xsd"/>
  
Please revert the ejb XSD back to only including jakartaee_9.xsd, as the EJB specification will not be updated to support the new features of Jakarta EE 10, and the scehma must remain campatible with Jakarta EE 9.
  
Updating the XSD for EJB to include jakartaee_10.xsd has effectively forced a spec revision, as it is requiring the EJB implementation to support new features added elsewhere in Jakarta EE 10.

**Comment by tkburroughs** [comment]
The same thing occurred for Java EE 7 & Java EE 8; both included EJB 3.2.  Looking at the Java EE 8 Schemas, the ejb-jar_3_2.xsd file still references javaee_7.xsd, and not javaee_8.xsd :

https://www.oracle.com/webfolder/technetwork/jsc/xml/ns/javaee/index.html#8

Updating the schema would result in EJB 4.0 applications that could not be deployed to a Jakarta EE 9 server, since the ejb-jar.xml file might contain types not compatible with EE 9.

**Comment by ederks85** [comment]
@tkburroughs I have created PR #35 with the modification
