### ISSUE TITLE
Is this only for XML schemas?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jakartaee-schemas#4]
I know especially for Jakarta EE 9 it is mostly XML schemas to refactor into the new namespace, but could this repository also hold other schemas especially JSON schemas in future versions?
There [the $id property](http://json-schema.org/understanding-json-schema/structuring.html#the-id-property) for a top-level schema should be an absolute-URI, with a domain that you control. For example, "jakarta.ee".

**Comment by ivargrimstad** [comment]
If there are any future platform level JSON schemas, this would be the place for it I guess. 
Schemas related to component specifications should be maintained in repositories under that particular specification project.

**Comment by keilw** [comment]
I think it remains to be seen, if JSON schemas would apply mostly to JSON-P or JSON-B (the most likely candidates) or something applies to the platform along the lines of configuration or deployment definitions etc. Are the versions planned to be in a folder structure like "jakartaee9" as it currently is? Then adding a new folder won't be a problem.

**Comment by ivargrimstad** [comment]
I think we should probably look over the folder structure a bit. It does not make sense to have a separate folder per version. That could be handled better with releases and tags.

I think you got your question answered, so this issue could be closed...?
